### ISSUE TITLE
Hi, do you have a resource for setting up Windi with Next?

### ISSUE THREAD

**Issue by SaM13997** [avatarfreak/frontend-todo-app#1]
HI, awesome project, 

I'm doing something similar as well, but I can't seem to figure out how to configure NextJS with Windi.

If you don't mind, can you please explain to me/ link a guide to do so?

Thanks

**Comment by avatarfreak** [comment]
Hello Sam, Thanks for dropping in. I hope, by now you have figured it out on configuring WindiCss. I just followed the official website of WindiCss. WindiCss plugin I used was for the  Webpack framework. If you are using Next js then you follow their instruction at [WindiCss](https://windicss.org/integrations/webpack.html). Or else check my next.config.js and windi.config.js file. You will get an idea. If you have further question feel free to reach me.

**Comment by SaM13997** [comment]
UnoCSS(WindiCSS's Successor) works with NextJS... though its not bug free enough to be used in prod
